Fix destination path for single file publishes [RHELDST-10431]
release-engineering/exodus-rsync pull request #175
Opened 2022-03-22 18:48 UTC by crungehottman

Prior to this commit, exodus-rsync mishandled the destination path
for single files:

```
$ exodus-rsync -vv ./src/test.txt exodus:/dest/test | grep
'Adding to publish object'
   • Adding to publish object  batch=1 item={/dest/test/test/src/test.txt
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 }
url=/dev/publish/8f3ac649-7949-475c-9d8b-19bf94cde772
```

Now, exodus-rsync produces the expected destination path for single
files:

```
$ exodus-rsync -vv ./src/test.txt exodus:/dest/test | grep
'Adding to publish object'
   • Adding to publish object  batch=1 item={/dest/test/test.txt
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 }
url=/dev/publish/426901cf-6b3a-4ee2-9458-f235f056c5c6
```

2022-03-22 19:01 UTC, negillett submitted a review, later dismissed

2022-03-22 22:09 UTC, rohanpm commented
This isn't quite doing what the issue suggested.

If we use rsync to publish: ./src/test.txt => somehost:/dest/test

Then the command as given is ambiguous:

1. If somehost:/dest/test does not exist, or exists but isn't a directory, this means: the destination path is /dest/test
2. If somehost:/dest/test is a directory, this means: the destination path is /dest/test/test.txt

Given there are no directories on exodus, it's not obvious how to resolve the ambiguity.  In the issue I suggested it could be implemented as always using case (1).  I think I suggested that because it looked like that's the behavior pubtools-exodus was coded to expect.  It looks like you implemented (2) though.

Did you have a particular reason for this?  I don't have a strong argument either way how it should work, but the behavior here and the expectation in pubtools-exodus will have to match.

2022-03-22 22:16 UTC, rohanpm requested changes
To spell it out a bit more:

- cdn-utils-staged will produce items with a dest such as /content/origin/files/sha256/eb/eb13167c23482190972788038f71162dd2e6afc9760c6d4c3d336472d37da612/myfile.iso
- so exodus-rsync will be invoked as: exodus-rsync /path/to/myfile.iso exodus:/content/origin/files/sha256/eb/eb13167c23482190972788038f71162dd2e6afc9760c6d4c3d336472d37da612/myfile.iso
- and we want that to write to /content/origin/files/sha256/eb/eb13167c23482190972788038f71162dd2e6afc9760c6d4c3d336472d37da612/myfile.iso , not /content/origin/files/sha256/eb/eb13167c23482190972788038f71162dd2e6afc9760c6d4c3d336472d37da612/myfile.iso/myfile.iso .

2022-03-23 21:16 UTC, rohanpm requested changes

2022-03-23 21:16 UTC, rohanpm commented on internal/cmd/exodus.go
> +		fileStat, _ := os.Stat(srcTree)
What's the ignored value?  An error?  We shouldn't be silently ignoring it.

If it's not convenient to deal with an error here, you might consider pushing the "is it a directory" check upwards, e.g. in the function which calls webURI (which seems to be only one place), you check if it's a directory there.  Then pass a srcTreeIsDir argument or something like that into this function.  It should probably be like that anyway, as this is going to stat() the same path for every single file we're dealing with, when we only need to do it once.

2022-03-24 22:18 UTC, rohanpm approved these changes

2022-03-25 13:55 UTC, merged